import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { delimiter, join } from 'path'
import { getLegacyGuiDataDirs } from './app-data-paths'

/**
 * Loopback CDP endpoint for the embedded browser panel.
 *
 * The port exists so the OMP `browser` tool can attach to the panel the user is
 * actually looking at, instead of launching its own invisible browser with no
 * logins. It is **on by default**, because the feature only means anything if
 * every model gets it without the user having to configure anything first.
 *
 * The cost is real and worth stating: a Chromium debugging port is
 * unauthenticated, so while it is open any local process that can reach
 * 127.0.0.1 can drive every webContents in the app, including the privileged
 * renderer. Users who do not want that turn it off in Settings, which sets
 * `browserCdpEnabled: false`.
 */
export const DEFAULT_BROWSER_CDP_PORT = 9333

/** Override the port without touching settings (useful for tests and second profiles). */
export const BROWSER_CDP_PORT_ENV = 'VESPI_BROWSER_CDP_PORT'

/** Generated into the GUI data dir on every launch; safe to delete. */
export const BROWSER_CDP_OVERLAY_FILE = 'omp-browser-cdp.yml'

/**
 * OMP reads this as a path-delimiter-separated list of config files it merges
 * on top of the profile's own `config.yml` — it appends, never replaces, so
 * pointing it at our overlay leaves user settings intact.
 */
const CONFIG_FILES_ENV = 'PI_CONFIG_FILES'

const SETTINGS_FILE_NAME = 'settings.json'

export function resolveBrowserCdpPort(env: NodeJS.ProcessEnv = process.env): number {
  const raw = env[BROWSER_CDP_PORT_ENV]?.trim()
  if (!raw) return DEFAULT_BROWSER_CDP_PORT
  const parsed = Number(raw)
  // Fall back rather than throw: a malformed override must not stop startup,
  // and silently binding an unexpected port would be worse than the default.
  if (!Number.isInteger(parsed) || parsed < 1 || parsed > 65535) return DEFAULT_BROWSER_CDP_PORT
  return parsed
}

/**
 * Whether the panel is reachable, read tolerantly from a parsed settings object.
 *
 * Enabled is the shipped default: the point of the feature is that *every*
 * model can drive the panel, so a fresh install with no settings file at all
 * must already have it. Only an explicit `false` turns it off, and an
 * unreadable value fails closed rather than silently enabling an
 * unauthenticated debugging port.
 */
export function browserCdpEnabledIn(parsedSettings: unknown): boolean {
  if (!parsedSettings || typeof parsedSettings !== 'object') return true
  const raw = (parsedSettings as { browserCdpEnabled?: unknown }).browserCdpEnabled
  if (raw === undefined) return true
  if (raw === false) return false
  if (raw === true) return true
  return false
}

/**
 * Candidate settings.json paths, most authoritative first. The canonical GUI
 * data dir wins; the legacy locations are only consulted when it has no
 * readable settings file (pre-migration installs).
 */
export function browserCdpSettingsCandidates(options: {
  guiDataDir: string
  appDataDir?: string
  homeDir?: string
}): string[] {
  const primary = join(options.guiDataDir, SETTINGS_FILE_NAME)
  const legacy = getLegacyGuiDataDirs({ appDataDir: options.appDataDir, homeDir: options.homeDir }).map(
    (dir) => join(dir, SETTINGS_FILE_NAME)
  )
  return [primary, ...legacy]
}

/** First readable settings file decides. Unreadable or invalid files are skipped. */
export function readBrowserCdpEnabled(
  candidates: string[],
  readFile: (path: string) => string = (path) => readFileSync(path, 'utf-8'),
  pathExists: (path: string) => boolean = existsSync
): boolean {
  for (const candidate of candidates) {
    if (!pathExists(candidate)) continue
    try {
      return browserCdpEnabledIn(JSON.parse(readFile(candidate)))
    } catch {
      // A truncated settings file fails closed: better to leave the port shut
      // and let the user re-enable it than to open one on a corrupt read.
      return false
    }
  }
  // No settings file at all is a fresh install, which ships with this on.
  return true
}

export function browserCdpOverlayPath(guiDataDir: string): string {
  return join(guiDataDir, BROWSER_CDP_OVERLAY_FILE)
}

/**
 * The overlay handed to OMP. Only `cdpUrl` is set: `browser.relay` takes
 * precedence over it and stays the user's choice, and `headless` is irrelevant
 * once we attach to an existing browser instead of launching one.
 */
export function browserCdpOverlayYaml(port: number): string {
  return [
    '# Generated by VesPi. Points the OMP browser tool at the embedded browser',
    '# panel instead of launching its own browser. Rewritten on every launch.',
    'browser:',
    `  cdpUrl: "http://127.0.0.1:${port}"`,
    '',
  ].join('\n')
}

/**
 * Append the overlay to PI_CONFIG_FILES without dropping an existing value —
 * a user who already points OMP at their own overlays keeps them.
 */
export function withConfigFilesEnv(
  existing: string | undefined,
  overlayPath: string,
  separator: string = delimiter
): string {
  const parts = (existing ?? '')
    .split(separator)
    .map((part) => part.trim())
    .filter(Boolean)
  if (!parts.includes(overlayPath)) parts.push(overlayPath)
  return parts.join(separator)
}

/** The PI_CONFIG_FILES value that points the kernel at the panel overlay. */
export function browserCdpConfigFilesValue(
  overlayPath: string,
  env: NodeJS.ProcessEnv = process.env
): string {
  return withConfigFilesEnv(env[CONFIG_FILES_ENV], overlayPath, delimiter)
}

export interface BrowserCdpInit {
  enabled: boolean
  port: number | null
  overlayPath: string | null
}

let kernelEnv: Record<string, string> = {}

/**
 * Env vars every kernel start needs so the browser tool attaches to the panel.
 * Empty until the panel is proven reachable, so nothing changes for users who
 * never opt in — and, more importantly, the kernel is never pointed at an
 * endpoint where the only thing it could pick is VesPi's own interface.
 */
export function browserCdpKernelEnv(): Record<string, string> {
  return { ...kernelEnv }
}

/** Test seam: clear the module state between cases. */
export function resetBrowserCdpState(): void {
  kernelEnv = {}
}

export interface CdpTargetInfo {
  type?: string
  url?: string
  title?: string
}

/**
 * The kernel's Electron attach path (`pickElectronTarget`) only ever considers
 * targets whose type is exactly `page`. A target the model must not drive —
 * VesPi's own renderer — is also a `page`, so "a page target exists" is not
 * enough: it has to be an http(s) target that is not this app's renderer.
 *
 * Returns null when nothing qualifies, which is the signal to keep the kernel
 * away from this endpoint entirely rather than let it fall back to driving the
 * application's own interface.
 */
export function pickPanelTarget(
  targets: CdpTargetInfo[],
  isAppRenderer: (url: string) => boolean
): CdpTargetInfo | null {
  for (const target of targets) {
    if (target.type !== 'page') continue
    const url = target.url
    if (typeof url !== 'string' || !/^https?:\/\//i.test(url)) continue
    if (isAppRenderer(url)) continue
    return target
  }
  return null
}

/** Cheap, sorted summary of what the endpoint is offering — for the app log. */
export function describeTargets(targets: CdpTargetInfo[]): string {
  const kinds = targets.map((target) => `${target.type ?? '?'}${target.url ? `:${trimUrl(target.url)}` : ''}`)
  return kinds.length > 0 ? kinds.sort().join(' | ') : '(none)'
}

function trimUrl(url: string): string {
  try {
    const parsed = new URL(url)
    return parsed.host || parsed.protocol
  } catch {
    return url.slice(0, 24)
  }
}

async function listCdpTargets(port: number): Promise<CdpTargetInfo[]> {
  const response = await fetch(`http://127.0.0.1:${port}/json/list`)
  if (!response.ok) return []
  const parsed: unknown = await response.json()
  return Array.isArray(parsed) ? (parsed as CdpTargetInfo[]) : []
}

export interface BrowserCdpWatchOptions {
  port: number
  isAppRenderer: (url: string) => boolean
  /** Full value to put in PI_CONFIG_FILES once the panel is drivable. */
  configFilesValue: string
  intervalMs?: number
  /** Test seams. */
  listTargets?: (port: number) => Promise<CdpTargetInfo[]>
  setTimer?: (fn: () => void, ms: number) => NodeJS.Timeout
  clearTimer?: (timer: NodeJS.Timeout) => void
  onStateChange?: (state: { attached: boolean; url: string | null; observed: string }) => void
}

/**
 * Keep the kernel pointed at this endpoint only while a drivable panel page is
 * actually present, and take the pointer away the moment it is not.
 *
 * This is a safety property, not a nicety: while the panel is a non-`page`
 * target, `pickElectronTarget` would happily select VesPi's own renderer
 * instead, and a model clicking the application's own interface is worse than
 * no browser at all. Re-evaluated continuously because the user can close the
 * panel or navigate it while a session is live.
 */
export function startBrowserCdpWatch(options: BrowserCdpWatchOptions): () => void {
  const interval = options.intervalMs ?? 3000
  const list = options.listTargets ?? listCdpTargets
  const setTimer = options.setTimer ?? ((fn, ms) => setTimeout(fn, ms))
  const clearTimer = options.clearTimer ?? ((timer) => clearTimeout(timer))

  let stopped = false
  let timer: NodeJS.Timeout | null = null
  let attached = false
  let lastObserved: string | null = null

  const stop = (): void => {
    stopped = true
    if (timer) clearTimer(timer)
    timer = null
    kernelEnv = {}
  }

  const tick = async (): Promise<void> => {
    if (stopped) return
    let targets: CdpTargetInfo[] = []
    try {
      targets = await list(options.port)
    } catch {
      // The endpoint is not up yet, or the app is shutting down. Treated the
      // same as "no panel": the kernel must not be pointed at it.
      targets = []
    }
    if (stopped) return

    const found = pickPanelTarget(targets, options.isAppRenderer)
    const observed = describeTargets(targets)
    const nextAttached = found !== null

    if (nextAttached) {
      // The overlay is inert unless PI_CONFIG_FILES points at it, so leave the
      // file in place and gate on the env instead.
      kernelEnv = { [CONFIG_FILES_ENV]: options.configFilesValue }
    } else {
      kernelEnv = {}
    }

    if (nextAttached !== attached || observed !== lastObserved) {
      attached = nextAttached
      lastObserved = observed
      options.onStateChange?.({ attached, url: found?.url ?? null, observed })
    }

    if (!stopped) timer = setTimer(() => void tick(), interval)
  }

  void tick()
  return stop
}

/**
 * Decide once at startup whether the panel's endpoint should be opened at all.
 * Called before `app.whenReady()` — the debugging port switch has to be set
 * before Chromium initialises.
 *
 * Returns the decision instead of calling `app.commandLine.appendSwitch`
 * itself, so this module stays free of Electron and remains unit-testable.
 * Wiring the kernel is deliberately *not* done here: it waits for the watch to
 * observe a drivable panel page.
 */
export function initBrowserCdp(options: {
  guiDataDir: string
  appDataDir?: string
  homeDir?: string
  env?: NodeJS.ProcessEnv
}): BrowserCdpInit {
  const env = options.env ?? process.env
  const disabled: BrowserCdpInit = { enabled: false, port: null, overlayPath: null }

  const enabled = readBrowserCdpEnabled(
    browserCdpSettingsCandidates({
      guiDataDir: options.guiDataDir,
      appDataDir: options.appDataDir,
      homeDir: options.homeDir,
    })
  )
  if (!enabled) {
    kernelEnv = {}
    return disabled
  }

  const port = resolveBrowserCdpPort(env)
  const overlayPath = browserCdpOverlayPath(options.guiDataDir)
  try {
    mkdirSync(options.guiDataDir, { recursive: true })
    writeFileSync(overlayPath, browserCdpOverlayYaml(port), 'utf-8')
  } catch {
    // An unwritable data dir must not stop the app from starting; the port
    // simply stays unusable because the kernel has no overlay to read.
    kernelEnv = {}
    return disabled
  }

  // Env stays empty until the watch proves the panel is drivable.
  kernelEnv = {}
  return { enabled: true, port, overlayPath }
}
